name: campus_marketplace
description: A new Flutter application for Campus Marketplace.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  http: ^1.1.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  cached_network_image: ^3.3.0
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/DormDeal.jpg"
